/**
 * v2.6.0 데이터 가져오기 통합 테스트
 * 실행: npx tsx src/test/integration/dataImport.test.ts
 *
 * 사전 요구사항: docker compose up -d
 */

import * as path from 'path';
import { ConnectionConfig, DataImportConfig, ColumnMapping, ParsedFileData } from '../../types/database';
import { MySQLProvider } from '../../providers/mysqlProvider';
import { PostgresProvider } from '../../providers/postgresProvider';
import { SQLiteProvider } from '../../providers/sqliteProvider';
import { H2Provider } from '../../providers/h2Provider';
import {
    parseCSV,
    parseJSON,
    parseExcel,
    suggestColumnMapping,
    importData,
} from '../../utils/dataImport';
import { DatabaseConnection } from '../../types/database';
import * as XLSX from 'xlsx';

// ── Helpers ─────────────────────────────────────

let totalPass = 0;
let totalFail = 0;
const failures: string[] = [];

function header(title: string) {
    console.log(`\n${'═'.repeat(60)}`);
    console.log(`  ${title}`);
    console.log(`${'═'.repeat(60)}`);
}

function pass(msg: string) {
    totalPass++;
    console.log(`  ✅ ${msg}`);
}

function fail(msg: string, err?: unknown) {
    totalFail++;
    const detail = err instanceof Error ? err.message : String(err ?? '');
    console.log(`  ❌ ${msg}${detail ? ' — ' + detail : ''}`);
    failures.push(`${msg}: ${detail}`);
}

async function assert(condition: boolean, msg: string) {
    if (condition) { pass(msg); } else { fail(msg); }
}

/** H2는 대문자 컬럼명 반환 — 대소문자 무관 접근 */
function getField(row: Record<string, unknown>, field: string): unknown {
    if (row[field] !== undefined) { return row[field]; }
    if (row[field.toUpperCase()] !== undefined) { return row[field.toUpperCase()]; }
    if (row[field.toLowerCase()] !== undefined) { return row[field.toLowerCase()]; }
    return undefined;
}

// ── Configs ─────────────────────────────────────

const sqlitePath = path.resolve(__dirname, '../../../test-data/import-test.db');

const configs: Record<string, ConnectionConfig> = {
    mysql: {
        id: 'imp-mysql', name: 'MySQL Import', type: 'mysql',
        host: 'localhost', port: 3306,
        username: 'root', password: 'root1234', database: 'mydb',
    },
    postgres: {
        id: 'imp-pg', name: 'PG Import', type: 'postgres',
        host: 'localhost', port: 5432,
        username: 'postgres', password: 'postgres1234', database: 'mydb',
    },
    sqlite: {
        id: 'imp-sqlite', name: 'SQLite Import', type: 'sqlite',
        host: '', port: 0, username: '',
        database: sqlitePath,
    },
    h2: {
        id: 'imp-h2', name: 'H2 Import', type: 'h2',
        host: 'localhost', port: 5435,
        username: 'sa', password: '',
        database: 'mem:importtest',
        h2Mode: { protocol: 'tcp', dbType: 'mem', dbPath: 'importtest' },
    },
};

// ── Test Data ───────────────────────────────────

function makeCsvBuffer(csv: string): Uint8Array {
    return new TextEncoder().encode(csv);
}

function makeJsonBuffer(data: unknown): Uint8Array {
    return new TextEncoder().encode(JSON.stringify(data));
}

function makeExcelBuffer(headers: string[], rows: unknown[][]): Uint8Array {
    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet([headers, ...rows]);
    XLSX.utils.book_append_sheet(wb, ws, 'Sheet1');
    return new Uint8Array(XLSX.write(wb, { type: 'array', bookType: 'xlsx' }));
}

// ── 공통 테스트 테이블 생성 ─────────────────────

async function setupTable(conn: DatabaseConnection, dbType: string, db?: string) {

    // 기존 테이블 삭제
    try { await conn.executeQuery('DROP TABLE IF EXISTS import_test', db); } catch { /* ok */ }

    let createSQL: string;
    switch (dbType) {
        case 'mysql':
            createSQL = `CREATE TABLE import_test (
                id INT PRIMARY KEY AUTO_INCREMENT,
                name VARCHAR(100) NOT NULL,
                age INT,
                email VARCHAR(200)
            )`;
            break;
        case 'postgres':
            createSQL = `CREATE TABLE import_test (
                id SERIAL PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                age INT,
                email VARCHAR(200)
            )`;
            break;
        case 'sqlite':
            createSQL = `CREATE TABLE import_test (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                age INTEGER,
                email TEXT
            )`;
            break;
        case 'h2':
            createSQL = `CREATE TABLE import_test (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                age INT,
                email VARCHAR(200)
            )`;
            break;
        default:
            throw new Error(`Unsupported: ${dbType}`);
    }

    await conn.executeQuery(createSQL, db);
}

// unique 제약 테이블
async function setupUniqueTable(conn: DatabaseConnection, dbType: string, db?: string) {
    try { await conn.executeQuery('DROP TABLE IF EXISTS import_unique', db); } catch { /* ok */ }

    let createSQL: string;
    switch (dbType) {
        case 'mysql':
            createSQL = `CREATE TABLE import_unique (
                id INT PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                val VARCHAR(200)
            )`;
            break;
        case 'postgres':
            createSQL = `CREATE TABLE import_unique (
                id INT PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                val VARCHAR(200)
            )`;
            break;
        case 'sqlite':
            createSQL = `CREATE TABLE import_unique (
                id INTEGER PRIMARY KEY,
                name TEXT NOT NULL,
                val TEXT
            )`;
            break;
        case 'h2':
            createSQL = `CREATE TABLE import_unique (
                id INT PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                val VARCHAR(200)
            )`;
            break;
        default:
            throw new Error(`Unsupported: ${dbType}`);
    }

    await conn.executeQuery(createSQL, db);
}

// ── DB별 테스트 ─────────────────────────────────

async function testImportForDB(
    dbLabel: string,
    conn: DatabaseConnection,
    dbType: string
) {
    header(`${dbLabel} — Data Import`);
    // H2는 database 파라미터를 전달하면 안 됨 (식별자 에러)
    const db = dbType === 'h2' ? undefined : conn.config.database;

    // 1. CSV 가져오기 (기본 INSERT)
    try {
        await setupTable(conn, dbType, db);
        const csv = 'name,age,email\nAlice,30,alice@test.com\nBob,25,bob@test.com\nCharlie,35,charlie@test.com\n';
        const parsed = parseCSV(makeCsvBuffer(csv), 'test.csv');

        await assert(parsed.totalRows === 3, `[${dbLabel}] CSV 파싱 3행`);

        const schema = await conn.getTableSchema('import_test', db);
        const mappings = suggestColumnMapping(parsed.headers, schema);

        // name, age, email 모두 매핑되어야 함
        const mappedCount = mappings.filter(m => m.targetColumn !== '').length;
        await assert(mappedCount === 3, `[${dbLabel}] 자동 매핑 3개`);

        const config: DataImportConfig = {
            tableName: 'import_test',
            database: db,
            columnMapping: mappings,
            conflictStrategy: 'skip',
            batchSize: 10,
            primaryKeyColumns: schema.filter(c => c.primaryKey).map(c => c.name),
        };

        const result = await importData(conn, parsed, config);
        await assert(result.inserted === 3, `[${dbLabel}] CSV INSERT 3행 삽입`);
        await assert(result.failed === 0, `[${dbLabel}] CSV INSERT 실패 0`);
        await assert(result.executionTime > 0, `[${dbLabel}] CSV 실행 시간 > 0`);

        // DB에서 검증
        const rows = await conn.executeQuery('SELECT COUNT(*) as cnt FROM import_test', db);
        const cnt = Number(getField(rows.rows[0] as Record<string, unknown>, 'cnt'));
        await assert(cnt === 3, `[${dbLabel}] DB 검증 3행`);
    } catch (e) { fail(`[${dbLabel}] CSV 가져오기`, e); }

    // 2. JSON 가져오기
    try {
        await setupTable(conn, dbType, db);
        const data = [
            { name: 'Dan', age: 28, email: 'dan@test.com' },
            { name: 'Eve', age: 32, email: 'eve@test.com' },
        ];
        const parsed = parseJSON(makeJsonBuffer(data), 'test.json');

        const schema = await conn.getTableSchema('import_test', db);
        const mappings = suggestColumnMapping(parsed.headers, schema);

        const config: DataImportConfig = {
            tableName: 'import_test',
            database: db,
            columnMapping: mappings,
            conflictStrategy: 'skip',
            batchSize: 10,
            primaryKeyColumns: schema.filter(c => c.primaryKey).map(c => c.name),
        };

        const result = await importData(conn, parsed, config);
        await assert(result.inserted === 2, `[${dbLabel}] JSON INSERT 2행`);
    } catch (e) { fail(`[${dbLabel}] JSON 가져오기`, e); }

    // 3. Excel 가져오기
    try {
        await setupTable(conn, dbType, db);
        const buf = makeExcelBuffer(
            ['name', 'age', 'email'],
            [['Frank', 40, 'frank@test.com'], ['Grace', 22, 'grace@test.com']]
        );
        const parsed = parseExcel(buf, 'test.xlsx');

        const schema = await conn.getTableSchema('import_test', db);
        const mappings = suggestColumnMapping(parsed.headers, schema);

        const config: DataImportConfig = {
            tableName: 'import_test',
            database: db,
            columnMapping: mappings,
            conflictStrategy: 'skip',
            batchSize: 10,
            primaryKeyColumns: schema.filter(c => c.primaryKey).map(c => c.name),
        };

        const result = await importData(conn, parsed, config);
        await assert(result.inserted === 2, `[${dbLabel}] Excel INSERT 2행`);
    } catch (e) { fail(`[${dbLabel}] Excel 가져오기`, e); }

    // 4. 충돌 처리 — skip
    try {
        await setupUniqueTable(conn, dbType, db);
        // 먼저 데이터 삽입
        await conn.executeQuery("INSERT INTO import_unique (id, name, val) VALUES (1, 'Alice', 'v1')", db);
        await conn.executeQuery("INSERT INTO import_unique (id, name, val) VALUES (2, 'Bob', 'v2')", db);

        const csv = 'id,name,val\n1,Alice-dup,v1-dup\n3,Charlie,v3\n';
        const parsed = parseCSV(makeCsvBuffer(csv), 'skip.csv');

        const schema = await conn.getTableSchema('import_unique', db);
        const mappings = suggestColumnMapping(parsed.headers, schema);

        const config: DataImportConfig = {
            tableName: 'import_unique',
            database: db,
            columnMapping: mappings,
            conflictStrategy: 'skip',
            batchSize: 10,
            primaryKeyColumns: ['id'],
        };

        const result = await importData(conn, parsed, config);
        // id=1은 중복으로 skip, id=3은 삽입
        await assert(result.inserted + result.skipped === 2, `[${dbLabel}] skip 전략 총 2건 처리`);

        // id=1의 name은 원래대로 Alice (덮어쓰지 않음)
        const check = await conn.executeQuery("SELECT name FROM import_unique WHERE id = 1", db);
        const name = getField(check.rows[0] as Record<string, unknown>, 'name');
        await assert(name === 'Alice', `[${dbLabel}] skip 시 기존 데이터 보존`);

        // id=3 삽입 확인
        const check3 = await conn.executeQuery("SELECT name FROM import_unique WHERE id = 3", db);
        await assert(check3.rows.length === 1, `[${dbLabel}] skip 새 행 삽입 성공`);
    } catch (e) { fail(`[${dbLabel}] skip 충돌 처리`, e); }

    // 5. 충돌 처리 — upsert
    try {
        await setupUniqueTable(conn, dbType, db);
        await conn.executeQuery("INSERT INTO import_unique (id, name, val) VALUES (1, 'Alice', 'old')", db);

        const csv = 'id,name,val\n1,Alice,new\n2,Bob,fresh\n';
        const parsed = parseCSV(makeCsvBuffer(csv), 'upsert.csv');

        const schema = await conn.getTableSchema('import_unique', db);
        const mappings = suggestColumnMapping(parsed.headers, schema);

        const config: DataImportConfig = {
            tableName: 'import_unique',
            database: db,
            columnMapping: mappings,
            conflictStrategy: 'upsert',
            batchSize: 10,
            primaryKeyColumns: ['id'],
        };

        const result = await importData(conn, parsed, config);
        await assert(result.failed === 0, `[${dbLabel}] upsert 실패 0`);

        // id=1의 value가 'new'로 업데이트됨
        const check = await conn.executeQuery("SELECT val FROM import_unique WHERE id = 1", db);
        const val = getField(check.rows[0] as Record<string, unknown>, 'val');
        await assert(val === 'new', `[${dbLabel}] upsert 기존 행 업데이트`);

        // id=2 삽입 확인
        const check2Rows = await conn.executeQuery("SELECT name FROM import_unique WHERE id = 2", db);
        await assert(check2Rows.rows.length === 1, `[${dbLabel}] upsert 새 행 삽입`);
    } catch (e) { fail(`[${dbLabel}] upsert 충돌 처리`, e); }

    // 6. 부분 컬럼 매핑 (일부 컬럼만)
    try {
        await setupTable(conn, dbType, db);
        const csv = 'name,extra_field\nOnlyName,ignored\n';
        const parsed = parseCSV(makeCsvBuffer(csv), 'partial.csv');

        const schema = await conn.getTableSchema('import_test', db);

        // name만 매핑, extra_field는 skip
        const mappings: ColumnMapping[] = [
            { sourceColumn: 'name', targetColumn: 'name', targetType: 'varchar' },
            { sourceColumn: 'extra_field', targetColumn: '', targetType: '' },
        ];

        const config: DataImportConfig = {
            tableName: 'import_test',
            database: db,
            columnMapping: mappings,
            conflictStrategy: 'skip',
            batchSize: 10,
            primaryKeyColumns: schema.filter(c => c.primaryKey).map(c => c.name),
        };

        const result = await importData(conn, parsed, config);
        await assert(result.inserted === 1, `[${dbLabel}] 부분 매핑 1행 삽입`);

        const check = await conn.executeQuery('SELECT name, age, email FROM import_test', db);
        const row = check.rows[0] as Record<string, unknown>;
        await assert(getField(row, 'name') === 'OnlyName', `[${dbLabel}] 부분 매핑 name 정확`);
        const ageVal = getField(row, 'age');
        await assert(ageVal === null || ageVal === undefined, `[${dbLabel}] 미매핑 컬럼 NULL`);
    } catch (e) { fail(`[${dbLabel}] 부분 컬럼 매핑`, e); }

    // 7. 대용량 배치 + 진행률 콜백
    try {
        await setupTable(conn, dbType, db);
        // 50행 데이터
        const rows: unknown[][] = [];
        for (let i = 0; i < 50; i++) {
            rows.push([`User${i}`, 20 + (i % 30), `user${i}@test.com`]);
        }
        const parsed: ParsedFileData = {
            headers: ['name', 'age', 'email'],
            rows,
            totalRows: 50,
            format: 'csv',
            fileName: 'bulk.csv',
        };

        const schema = await conn.getTableSchema('import_test', db);
        const mappings = suggestColumnMapping(parsed.headers, schema);

        let progressCallCount = 0;
        let lastProgress = { current: 0, total: 0 };

        const config: DataImportConfig = {
            tableName: 'import_test',
            database: db,
            columnMapping: mappings,
            conflictStrategy: 'skip',
            batchSize: 10, // 50행 / 10 = 5 배치
            primaryKeyColumns: schema.filter(c => c.primaryKey).map(c => c.name),
        };

        const result = await importData(conn, parsed, config, (p) => {
            progressCallCount++;
            lastProgress = { current: p.current, total: p.total };
        });

        await assert(result.inserted === 50, `[${dbLabel}] 대용량 50행 삽입`);
        await assert(progressCallCount >= 5, `[${dbLabel}] 진행률 콜백 5회 이상 (${progressCallCount}회)`);
        await assert(lastProgress.current === 50, `[${dbLabel}] 최종 진행률 current=50`);
        await assert(lastProgress.total === 50, `[${dbLabel}] 최종 진행률 total=50`);
    } catch (e) { fail(`[${dbLabel}] 대용량 배치 + 진행률`, e); }

    // 8. NULL 값 처리
    try {
        await setupTable(conn, dbType, db);
        const csv = 'name,age,email\nNoAge,,\nNoEmail,25,\n';
        const parsed = parseCSV(makeCsvBuffer(csv), 'nulls.csv');

        const schema = await conn.getTableSchema('import_test', db);
        const mappings = suggestColumnMapping(parsed.headers, schema);

        const config: DataImportConfig = {
            tableName: 'import_test',
            database: db,
            columnMapping: mappings,
            conflictStrategy: 'skip',
            batchSize: 10,
            primaryKeyColumns: schema.filter(c => c.primaryKey).map(c => c.name),
        };

        const result = await importData(conn, parsed, config);
        await assert(result.inserted === 2, `[${dbLabel}] NULL 값 2행 삽입`);

        const check = await conn.executeQuery("SELECT age, email FROM import_test WHERE name = 'NoAge'", db);
        const row = check.rows[0] as Record<string, unknown>;
        const ageVal2 = getField(row, 'age');
        await assert(ageVal2 === null || ageVal2 === undefined, `[${dbLabel}] NULL age 보존`);
    } catch (e) { fail(`[${dbLabel}] NULL 값 처리`, e); }

    // 9. 특수 문자 (한국어, 싱글쿼트)
    try {
        await setupTable(conn, dbType, db);
        const csv = "name,age,email\n홍길동,30,hong@test.com\nO'Brien,40,ob@test.com\n";
        const parsed = parseCSV(makeCsvBuffer(csv), 'special.csv');

        const schema = await conn.getTableSchema('import_test', db);
        const mappings = suggestColumnMapping(parsed.headers, schema);

        const config: DataImportConfig = {
            tableName: 'import_test',
            database: db,
            columnMapping: mappings,
            conflictStrategy: 'skip',
            batchSize: 10,
            primaryKeyColumns: schema.filter(c => c.primaryKey).map(c => c.name),
        };

        const result = await importData(conn, parsed, config);
        await assert(result.inserted === 2, `[${dbLabel}] 특수 문자 2행 삽입`);

        const check = await conn.executeQuery("SELECT name FROM import_test ORDER BY age", db);
        const names = check.rows.map(r => getField(r as Record<string, unknown>, 'name'));
        await assert(names.includes('홍길동'), `[${dbLabel}] 한국어 이름 보존`);
        await assert(names.some(n => String(n).includes("O'Brien")), `[${dbLabel}] 싱글쿼트 이스케이프`);
    } catch (e) { fail(`[${dbLabel}] 특수 문자`, e); }

    // 10. 매핑 없음 오류
    try {
        await setupTable(conn, dbType, db);
        const csv = 'a,b\n1,2\n';
        const parsed = parseCSV(makeCsvBuffer(csv), 'nomapping.csv');

        const config: DataImportConfig = {
            tableName: 'import_test',
            database: db,
            columnMapping: [
                { sourceColumn: 'a', targetColumn: '', targetType: '' },
                { sourceColumn: 'b', targetColumn: '', targetType: '' },
            ],
            conflictStrategy: 'skip',
            batchSize: 10,
        };

        try {
            await importData(conn, parsed, config);
            fail(`[${dbLabel}] 매핑 없음 오류 미발생`);
        } catch (e) {
            const msg = (e as Error).message;
            await assert(msg.includes('No columns mapped'), `[${dbLabel}] 매핑 없음 오류 메시지`);
        }
    } catch (e) { fail(`[${dbLabel}] 매핑 없음 테스트`, e); }
}

// ── Main ────────────────────────────────────────

async function main() {
    console.log('╔══════════════════════════════════════════════════════════╗');
    console.log('║  DBunny v2.6.0 Data Import Integration Tests           ║');
    console.log('╚══════════════════════════════════════════════════════════╝');

    // MySQL
    {
        const conn = new MySQLProvider(configs.mysql);
        try {
            await conn.connect();
            await testImportForDB('MySQL', conn, 'mysql');
        } catch (e) { fail('MySQL connect', e); }
        try { await conn.disconnect(); } catch { /* ok */ }
    }

    // PostgreSQL
    {
        const conn = new PostgresProvider(configs.postgres);
        try {
            await conn.connect();
            await testImportForDB('PostgreSQL', conn, 'postgres');
        } catch (e) { fail('PostgreSQL connect', e); }
        try { await conn.disconnect(); } catch { /* ok */ }
    }

    // SQLite
    {
        const conn = new SQLiteProvider(configs.sqlite);
        try {
            await conn.connect();
            await testImportForDB('SQLite', conn, 'sqlite');
        } catch (e) { fail('SQLite connect', e); }
        try { await conn.disconnect(); } catch { /* ok */ }
    }

    // H2
    {
        const conn = new H2Provider(configs.h2);
        try {
            await conn.connect();
            await testImportForDB('H2', conn, 'h2');
        } catch (e) { fail('H2 connect', e); }
        try { await conn.disconnect(); } catch { /* ok */ }
    }

    // ── 결과 ──
    console.log(`\n${'═'.repeat(60)}`);
    console.log(`  Total: ${totalPass + totalFail} | ✅ Passed: ${totalPass} | ❌ Failed: ${totalFail}`);
    if (failures.length > 0) {
        console.log('\n  Failed tests:');
        failures.forEach(f => console.log(`    - ${f}`));
    }
    console.log(`${'═'.repeat(60)}`);

    process.exit(totalFail > 0 ? 1 : 0);
}

main().catch(e => {
    console.error('Fatal error:', e);
    process.exit(1);
});
