/**
 * v2.9.0 데이터 통계 패널 통합 테스트
 * 실행: npx tsx src/test/integration/dataStatistics.test.ts
 *
 * 사전 요구사항: docker compose up -d
 */

import * as path from 'path';
import { ConnectionConfig, DatabaseConnection } from '../../types/database';
import { MySQLProvider } from '../../providers/mysqlProvider';
import { PostgresProvider } from '../../providers/postgresProvider';
import { SQLiteProvider } from '../../providers/sqliteProvider';
import { H2Provider } from '../../providers/h2Provider';
import {
    collectTableStatistics,
    buildRowCountQuery,
    buildColumnStatsQuery,
    buildNumericStatsQuery,
    buildTopValuesQuery,
    escapeIdentifier,
    isNumericType,
} from '../../utils/dataStatistics';

// ── Helpers ─────────────────────────────────────

let totalPass = 0;
let totalFail = 0;
const failures: string[] = [];

function header(title: string) {
    console.log(`\n${'═'.repeat(60)}`);
    console.log(`  ${title}`);
    console.log(`${'═'.repeat(60)}`);
}

function pass(msg: string) {
    totalPass++;
    console.log(`  ✅ ${msg}`);
}

function fail(msg: string, err?: unknown) {
    totalFail++;
    const detail = err instanceof Error ? err.message : String(err ?? '');
    console.log(`  ❌ ${msg}${detail ? ' — ' + detail : ''}`);
    failures.push(`${msg}: ${detail}`);
}

function assert(condition: boolean, msg: string) {
    if (condition) { pass(msg); } else { fail(msg); }
}

function assertEqual(actual: unknown, expected: unknown, msg: string) {
    if (actual === expected) { pass(msg); }
    else { fail(`${msg} — expected: ${JSON.stringify(expected)}, got: ${JSON.stringify(actual)}`); }
}

// ── Configs ─────────────────────────────────────

const sqlitePath = path.resolve(__dirname, '../../../test-data/statistics-test.db');

const configs: Record<string, ConnectionConfig> = {
    mysql: {
        id: 'stat-mysql', name: 'MySQL Stats', type: 'mysql',
        host: 'localhost', port: 3306,
        username: 'root', password: 'root1234', database: 'mydb',
    },
    postgres: {
        id: 'stat-pg', name: 'PG Stats', type: 'postgres',
        host: 'localhost', port: 5432,
        username: 'postgres', password: 'postgres1234', database: 'mydb',
    },
    sqlite: {
        id: 'stat-sqlite', name: 'SQLite Stats', type: 'sqlite',
        host: '', port: 0, username: '',
        database: sqlitePath,
    },
    h2: {
        id: 'stat-h2', name: 'H2 Stats', type: 'h2',
        host: 'localhost', port: 5435,
        username: 'sa', password: '',
        database: 'mem:statstest',
        h2Mode: { protocol: 'tcp', dbType: 'mem', dbPath: 'statstest' },
    },
};

// ── 테이블 준비 ─────────────────────────────────

async function setupTable(conn: DatabaseConnection, dbType: string, db?: string) {
    try { await conn.executeQuery('DROP TABLE IF EXISTS stat_test', db); } catch { /* ok */ }

    let sql: string;
    switch (dbType) {
        case 'mysql':
            sql = `CREATE TABLE stat_test (
                id INT PRIMARY KEY AUTO_INCREMENT,
                name VARCHAR(100) NOT NULL,
                age INT,
                salary DECIMAL(10,2),
                department VARCHAR(50),
                email VARCHAR(200)
            )`;
            break;
        case 'postgres':
            sql = `CREATE TABLE stat_test (
                id SERIAL PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                age INT,
                salary DECIMAL(10,2),
                department VARCHAR(50),
                email VARCHAR(200)
            )`;
            break;
        case 'sqlite':
            sql = `CREATE TABLE stat_test (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                age INTEGER,
                salary REAL,
                department TEXT,
                email TEXT
            )`;
            break;
        case 'h2':
            sql = `CREATE TABLE stat_test (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                age INT,
                salary DECIMAL(10,2),
                department VARCHAR(50),
                email VARCHAR(200)
            )`;
            break;
        default:
            throw new Error(`Unsupported: ${dbType}`);
    }

    await conn.executeQuery(sql, db);

    // 20행 데이터 삽입
    const data = [
        { name: 'Alice', age: 30, salary: 5000.00, dept: 'Engineering', email: 'alice@test.com' },
        { name: 'Bob', age: 25, salary: 4500.00, dept: 'Engineering', email: 'bob@test.com' },
        { name: 'Charlie', age: 35, salary: 6000.00, dept: 'Engineering', email: null },
        { name: 'Diana', age: 28, salary: 4800.00, dept: 'Design', email: 'diana@test.com' },
        { name: 'Eve', age: 32, salary: 5500.00, dept: 'Design', email: 'eve@test.com' },
        { name: 'Frank', age: 45, salary: 8000.00, dept: 'Management', email: null },
        { name: 'Grace', age: 27, salary: 4600.00, dept: 'Engineering', email: 'grace@test.com' },
        { name: 'Hank', age: 38, salary: 5800.00, dept: 'Design', email: 'hank@test.com' },
        { name: 'Ivy', age: 29, salary: 4900.00, dept: 'Marketing', email: 'ivy@test.com' },
        { name: 'Jack', age: 33, salary: 5200.00, dept: 'Marketing', email: null },
        { name: 'Kate', age: 26, salary: 4400.00, dept: 'Engineering', email: 'kate@test.com' },
        { name: 'Leo', age: 40, salary: 7000.00, dept: 'Management', email: 'leo@test.com' },
        { name: 'Mia', age: 31, salary: 5100.00, dept: 'Design', email: 'mia@test.com' },
        { name: '홍길동', age: 34, salary: 5300.00, dept: 'Engineering', email: 'hong@test.com' },
        { name: "O'Brien", age: 36, salary: 5700.00, dept: 'Marketing', email: null },
        { name: 'Pat', age: null, salary: null, dept: null, email: null },
        { name: 'Quinn', age: 22, salary: 3800.00, dept: 'Engineering', email: 'quinn@test.com' },
        { name: 'Rose', age: 41, salary: 7200.00, dept: 'Management', email: 'rose@test.com' },
        { name: 'Sam', age: 24, salary: 4200.00, dept: 'Marketing', email: 'sam@test.com' },
        { name: 'Tina', age: 37, salary: 5900.00, dept: 'Design', email: 'tina@test.com' },
    ];

    for (const d of data) {
        const nameVal = d.name.replace(/'/g, "''");
        const ageVal = d.age !== null ? String(d.age) : 'NULL';
        const salaryVal = d.salary !== null ? String(d.salary) : 'NULL';
        const deptVal = d.dept !== null ? `'${d.dept}'` : 'NULL';
        const emailVal = d.email !== null ? `'${d.email}'` : 'NULL';
        await conn.executeQuery(
            `INSERT INTO stat_test (name, age, salary, department, email) VALUES ('${nameVal}', ${ageVal}, ${salaryVal}, ${deptVal}, ${emailVal})`,
            db
        );
    }
}

async function cleanup(conn: DatabaseConnection, db?: string) {
    try { await conn.executeQuery('DROP TABLE IF EXISTS stat_test', db); } catch { /* ok */ }
}

// ── 유닛 테스트 (쿼리 빌더) ─────────────────────

function testQueryBuilders() {
    header('Query Builder — Unit Tests');

    // escapeIdentifier
    assertEqual(escapeIdentifier('users', 'mysql'), '`users`', 'MySQL 백틱');
    assertEqual(escapeIdentifier('users', 'postgres'), '"users"', 'PG 큰따옴표');
    assertEqual(escapeIdentifier('users', 'sqlite'), '"users"', 'SQLite 큰따옴표');
    assertEqual(escapeIdentifier('users', 'h2'), '"users"', 'H2 큰따옴표');

    // isNumericType
    assert(isNumericType('INT'), 'INT → numeric');
    assert(isNumericType('decimal(10,2)'), 'decimal → numeric');
    assert(isNumericType('FLOAT'), 'FLOAT → numeric');
    assert(isNumericType('BIGSERIAL'), 'BIGSERIAL → numeric');
    assert(!isNumericType('VARCHAR(100)'), 'VARCHAR → not numeric');
    assert(!isNumericType('TEXT'), 'TEXT → not numeric');
    assert(!isNumericType('DATE'), 'DATE → not numeric');

    // buildRowCountQuery
    const rcq = buildRowCountQuery('users', 'mysql');
    assert(rcq.includes('COUNT(*)'), 'rowCount에 COUNT(*) 포함');
    assert(rcq.includes('`users`'), 'rowCount에 테이블명 포함');

    // buildColumnStatsQuery
    const csq = buildColumnStatsQuery('users', 'age', 'postgres');
    assert(csq.includes('COUNT(*)'), 'colStats에 COUNT(*) 포함');
    assert(csq.includes('COUNT(DISTINCT'), 'colStats에 DISTINCT 포함');
    assert(csq.includes('"age"'), 'colStats에 컬럼명 포함');

    // buildNumericStatsQuery
    const nsq = buildNumericStatsQuery('users', 'salary', 'mysql');
    assert(nsq.includes('MIN('), 'numStats에 MIN 포함');
    assert(nsq.includes('MAX('), 'numStats에 MAX 포함');
    assert(nsq.includes('AVG('), 'numStats에 AVG 포함');

    // buildTopValuesQuery
    const tvq = buildTopValuesQuery('users', 'dept', 'sqlite', 5);
    assert(tvq.includes('GROUP BY'), 'topValues에 GROUP BY 포함');
    assert(tvq.includes('ORDER BY cnt DESC'), 'topValues에 ORDER BY 포함');
    assert(tvq.includes('LIMIT 5'), 'topValues에 LIMIT 5 포함');
}

// ── DB별 통합 테스트 ────────────────────────────

async function testForDB(
    label: string,
    conn: DatabaseConnection,
    dbType: string
) {
    header(`${label} — Data Statistics`);
    const db = dbType === 'h2' ? undefined : conn.config.database;

    try {
        await setupTable(conn, dbType, db);
    } catch (e) {
        fail(`[${label}] 테이블 준비 실패`, e);
        return;
    }

    // collectTableStatistics 전체 테스트
    try {
        const schema = await conn.getTableSchema('stat_test', db);
        const stats = await collectTableStatistics(conn, 'stat_test', schema, dbType, db);

        // 기본 정보
        assertEqual(stats.tableName, 'stat_test', `[${label}] 테이블명`);
        assertEqual(stats.totalRows, 20, `[${label}] 총 행 수 20`);
        assert(stats.columnCount >= 5, `[${label}] 컬럼 5개 이상`);
        assert(stats.executionTime > 0, `[${label}] 실행 시간 > 0`);

        // name 컬럼 — NOT NULL → nullCount=0
        const nameStat = stats.columns.find(c => c.columnName.toLowerCase() === 'name');
        assert(nameStat !== undefined, `[${label}] name 통계 존재`);
        if (nameStat) {
            assertEqual(nameStat.nullCount, 0, `[${label}] name NULL 0개`);
            assertEqual(nameStat.nullPercent, 0, `[${label}] name NULL 비율 0%`);
            assertEqual(nameStat.distinctCount, 20, `[${label}] name distinct 20개`);
            assert(nameStat.topValues.length > 0, `[${label}] name 빈출값 존재`);
        }

        // age 컬럼 — 1개 NULL (Pat)
        const ageStat = stats.columns.find(c => c.columnName.toLowerCase() === 'age');
        assert(ageStat !== undefined, `[${label}] age 통계 존재`);
        if (ageStat) {
            assertEqual(ageStat.nullCount, 1, `[${label}] age NULL 1개`);
            assertEqual(ageStat.nullPercent, 5, `[${label}] age NULL 비율 5%`);
            // min=22 (Quinn), max=45 (Frank)
            assertEqual(Number(ageStat.min), 22, `[${label}] age MIN=22`);
            assertEqual(Number(ageStat.max), 45, `[${label}] age MAX=45`);
            assert(ageStat.avg !== undefined, `[${label}] age AVG 존재`);
            // AVG(all ages except NULL) = (30+25+35+28+32+45+27+38+29+33+26+40+31+34+36+22+41+24+37) / 19
            // = 613/19 ≈ 32.26
            assert(ageStat.avg! >= 32 && ageStat.avg! <= 33, `[${label}] age AVG ≈ 32.26`);
        }

        // salary 컬럼 — 1개 NULL
        const salStat = stats.columns.find(c => c.columnName.toLowerCase() === 'salary');
        assert(salStat !== undefined, `[${label}] salary 통계 존재`);
        if (salStat) {
            assertEqual(salStat.nullCount, 1, `[${label}] salary NULL 1개`);
            assert(Number(salStat.min) >= 3800, `[${label}] salary MIN ≈ 3800`);
            assert(Number(salStat.max) >= 8000, `[${label}] salary MAX ≈ 8000`);
        }

        // department 컬럼 — 5개 고유값 (Engineering, Design, Management, Marketing, NULL)
        const deptStat = stats.columns.find(c => c.columnName.toLowerCase() === 'department');
        assert(deptStat !== undefined, `[${label}] department 통계 존재`);
        if (deptStat) {
            assertEqual(deptStat.nullCount, 1, `[${label}] department NULL 1개`);
            assertEqual(deptStat.distinctCount, 4, `[${label}] department distinct 4개`);
            // 빈출값: Engineering이 가장 많음 (7명)
            assert(deptStat.topValues.length >= 4, `[${label}] department 빈출값 4개 이상`);
            if (deptStat.topValues.length > 0) {
                assertEqual(deptStat.topValues[0].value, 'Engineering', `[${label}] department 최빈값=Engineering`);
                assertEqual(deptStat.topValues[0].count, 7, `[${label}] Engineering 7명`);
            }
        }

        // email 컬럼 — 5개 NULL
        const emailStat = stats.columns.find(c => c.columnName.toLowerCase() === 'email');
        assert(emailStat !== undefined, `[${label}] email 통계 존재`);
        if (emailStat) {
            assertEqual(emailStat.nullCount, 5, `[${label}] email NULL 5개`);
            assertEqual(emailStat.nullPercent, 25, `[${label}] email NULL 비율 25%`);
        }
    } catch (e) { fail(`[${label}] collectTableStatistics`, e); }

    // 빈 테이블 통계
    try {
        await conn.executeQuery('DELETE FROM stat_test', db);
        const schema = await conn.getTableSchema('stat_test', db);
        const stats = await collectTableStatistics(conn, 'stat_test', schema, dbType, db);

        assertEqual(stats.totalRows, 0, `[${label}] 빈 테이블 행 수 0`);
        for (const col of stats.columns) {
            assertEqual(col.nullCount, 0, `[${label}] 빈 테이블 ${col.columnName} NULL 0`);
            assertEqual(col.distinctCount, 0, `[${label}] 빈 테이블 ${col.columnName} distinct 0`);
        }
    } catch (e) { fail(`[${label}] 빈 테이블 통계`, e); }

    try { await cleanup(conn, db); } catch { /* ok */ }
}

// ── 실행 ────────────────────────────────────────

async function main() {
    console.log('╔══════════════════════════════════════════════════════════╗');
    console.log('║  DBunny v2.9.0 Data Statistics Integration Tests       ║');
    console.log('╚══════════════════════════════════════════════════════════╝');

    // 유닛 테스트 (쿼리 빌더)
    testQueryBuilders();

    // DB별 통합 테스트
    const providers = [
        { label: 'MySQL', config: configs.mysql, ProviderClass: MySQLProvider, dbType: 'mysql' },
        { label: 'PostgreSQL', config: configs.postgres, ProviderClass: PostgresProvider, dbType: 'postgres' },
        { label: 'SQLite', config: configs.sqlite, ProviderClass: SQLiteProvider, dbType: 'sqlite' },
        { label: 'H2', config: configs.h2, ProviderClass: H2Provider, dbType: 'h2' },
    ];

    for (const p of providers) {
        const provider = new p.ProviderClass(p.config);
        try {
            await provider.connect();
            await testForDB(p.label, provider, p.dbType);
            await provider.disconnect();
        } catch (e) {
            fail(`[${p.label}] 연결 실패`, e);
            try { await provider.disconnect(); } catch { /* ok */ }
        }
    }

    console.log(`\n${'═'.repeat(60)}`);
    console.log(`  Total: ${totalPass + totalFail} | ✅ Passed: ${totalPass} | ❌ Failed: ${totalFail}`);
    if (failures.length > 0) {
        console.log(`\n  Failed tests:`);
        failures.forEach(f => console.log(`    - ${f}`));
    }
    console.log(`${'═'.repeat(60)}`);

    process.exit(totalFail > 0 ? 1 : 0);
}

main();
